export const skillCategories = [
  {
    name: "Technology",
    skills: [
      "JavaScript",
      "Python",
      "React",
      "Node.js",
      "HTML/CSS",
      "Data Science",
      "Machine Learning",
      "iOS Development",
      "Android Development",
      "Cloud Computing",
      "DevOps",
      "Blockchain",
      "Cybersecurity",
      "UI/UX Design",
      "Game Development",
      "SQL",
      "Java",
      "C#",
      "PHP",
      "Ruby",
      "TypeScript",
      "Swift",
      "Kotlin",
      "Go",
      "Rust",
      "Docker",
      "Kubernetes",
      "AWS",
      "Azure",
      "Google Cloud",
      "GraphQL",
      "MongoDB",
      "PostgreSQL",
      "Firebase",
      "WordPress",
      "SEO",
      "Digital Marketing",
      "Data Analysis",
      "Excel",
      "Tableau",
      "Power BI",
    ],
  },
  {
    name: "Creative",
    skills: [
      "Photography",
      "Graphic Design",
      "Video Editing",
      "Animation",
      "Illustration",
      "Creative Writing",
      "Content Creation",
      "Music Production",
      "Drawing",
      "Painting",
      "Sculpture",
      "Pottery",
      "Calligraphy",
      "Typography",
      "Fashion Design",
      "Interior Design",
      "3D Modeling",
      "Photoshop",
      "Illustrator",
      "InDesign",
      "After Effects",
      "Premiere Pro",
      "Blender",
      "Maya",
      "Cinema 4D",
      "Procreate",
      "Lightroom",
      "Filmmaking",
      "Screenwriting",
      "Copywriting",
      "Branding",
      "Logo Design",
      "Web Design",
      "UX Writing",
      "Social Media Content",
    ],
  },
  {
    name: "Business",
    skills: [
      "Marketing",
      "Project Management",
      "Public Speaking",
      "Leadership",
      "Entrepreneurship",
      "Sales",
      "Negotiation",
      "Financial Planning",
      "Accounting",
      "Business Strategy",
      "Human Resources",
      "Customer Service",
      "Operations Management",
      "Supply Chain",
      "Business Analysis",
      "Product Management",
      "Agile Methodology",
      "Scrum",
      "Lean Six Sigma",
      "Business Development",
      "Fundraising",
      "Venture Capital",
      "Startups",
      "E-commerce",
      "Retail Management",
      "Real Estate",
      "Investment",
      "Stock Trading",
      "Cryptocurrency",
      "Taxation",
      "Business Law",
      "International Business",
      "Import/Export",
      "Consulting",
      "Event Planning",
    ],
  },
  {
    name: "Languages",
    skills: [
      "English",
      "Spanish",
      "French",
      "German",
      "Chinese (Mandarin)",
      "Japanese",
      "Korean",
      "Italian",
      "Portuguese",
      "Russian",
      "Arabic",
      "Hindi",
      "Turkish",
      "Dutch",
      "Swedish",
      "Norwegian",
      "Danish",
      "Finnish",
      "Greek",
      "Hebrew",
      "Polish",
      "Czech",
      "Hungarian",
      "Thai",
      "Vietnamese",
      "Indonesian",
      "Malay",
      "Tagalog",
      "Swahili",
      "Latin",
      "Sign Language",
      "Esperanto",
    ],
  },
  {
    name: "Lifestyle",
    skills: [
      "Cooking",
      "Baking",
      "Nutrition",
      "Fitness",
      "Yoga",
      "Meditation",
      "Gardening",
      "Home Improvement",
      "Interior Decorating",
      "Personal Finance",
      "Travel Planning",
      "Wine Tasting",
      "Cocktail Making",
      "Coffee Brewing",
      "Fashion Styling",
      "Makeup",
      "Skincare",
      "Hair Styling",
      "Sustainable Living",
      "Minimalism",
      "Parenting",
      "Pet Training",
      "Car Maintenance",
      "Bike Repair",
      "Camping",
      "Hiking",
      "Survival Skills",
      "First Aid",
      "Self Defense",
      "Organization",
      "Time Management",
      "Productivity",
      "Stress Management",
      "Public Speaking",
      "Networking",
    ],
  },
  {
    name: "Music & Performance",
    skills: [
      "Piano",
      "Guitar",
      "Violin",
      "Drums",
      "Singing",
      "Music Theory",
      "DJing",
      "Music Composition",
      "Songwriting",
      "Acting",
      "Dancing",
      "Ballet",
      "Hip Hop Dance",
      "Salsa",
      "Tango",
      "Ballroom Dance",
      "Contemporary Dance",
      "Theater",
      "Improv",
      "Stand-up Comedy",
      "Voice Acting",
      "Public Speaking",
      "Storytelling",
      "Saxophone",
      "Trumpet",
      "Flute",
      "Cello",
      "Bass Guitar",
      "Ukulele",
      "Harmonica",
      "Beatboxing",
      "Opera",
      "Musical Theater",
      "Conducting",
      "Sound Engineering",
    ],
  },
  {
    name: "Academic",
    skills: [
      "Mathematics",
      "Physics",
      "Chemistry",
      "Biology",
      "History",
      "Literature",
      "Philosophy",
      "Psychology",
      "Sociology",
      "Anthropology",
      "Economics",
      "Political Science",
      "Geography",
      "Astronomy",
      "Environmental Science",
      "Geology",
      "Statistics",
      "Research Methods",
      "Academic Writing",
      "Critical Thinking",
      "Logic",
      "Debate",
      "Essay Writing",
      "Thesis Development",
      "Citation Methods",
      "Study Skills",
      "Test Preparation",
      "SAT Prep",
      "GRE Prep",
      "GMAT Prep",
      "LSAT Prep",
      "MCAT Prep",
      "College Admissions",
      "Scholarship Applications",
      "Grant Writing",
    ],
  },
  {
    name: "Sports",
    skills: [
      "Soccer/Football",
      "Basketball",
      "Tennis",
      "Golf",
      "Swimming",
      "Running",
      "Cycling",
      "Volleyball",
      "Baseball",
      "Cricket",
      "Rugby",
      "Hockey",
      "Martial Arts",
      "Boxing",
      "Wrestling",
      "Yoga",
      "Pilates",
      "CrossFit",
      "Weight Training",
      "Rock Climbing",
      "Surfing",
      "Skateboarding",
      "Snowboarding",
      "Skiing",
      "Archery",
      "Fencing",
      "Table Tennis",
      "Badminton",
      "Bowling",
      "Sailing",
      "Rowing",
      "Canoeing",
      "Horseback Riding",
      "Figure Skating",
      "Gymnastics",
    ],
  },
  {
    name: "Crafts & DIY",
    skills: [
      "Knitting",
      "Crochet",
      "Sewing",
      "Embroidery",
      "Quilting",
      "Woodworking",
      "Carpentry",
      "Furniture Making",
      "Upholstery",
      "Jewelry Making",
      "Metalworking",
      "Leathercraft",
      "Bookbinding",
      "Paper Crafts",
      "Origami",
      "Scrapbooking",
      "Candle Making",
      "Soap Making",
      "Pottery",
      "Glass Blowing",
      "Stained Glass",
      "Mosaic",
      "Macramé",
      "Weaving",
      "Basket Making",
      "Floral Arrangement",
      "Terrarium Building",
      "Model Building",
      "Miniature Painting",
      "Costume Making",
      "Prop Making",
      "Home Brewing",
      "Wine Making",
      "Cheese Making",
      "Fermentation",
    ],
  },
]
